[package]
name = "passucks"
version = "0.1.0"
edition = "2021"
authors = ["Rares Goidescu <rares.goidescu@protonmail.com"]
license = "MIT"

[dependencies]
dirs = "5.0.1"
rand = "0.8.x"
rpassword = "7.3.1"
